# frozen_string_literal: true

source 'https://rubygems.org'

gem 'karafka', '>= 2.2.1'
gem 'karafka-web'
gem 'puma'
gem 'rails', '~> 7.0'
gem 'pg'

group :development, :test do
  gem 'karafka-testing'
  gem 'rspec'
end
