version: 0.0
os: linux
files:
  - source: /application
    destination: /home/ubuntu
permissions:
  - object: /home/ubuntu
    pattern: “**”
    owner: ubuntu
    group: ubuntu
    mode: 775
hooks:
  BeforeInstall:
    - location: scripts/install_docker.sh
      runas: ubuntu
    - location: scripts/install_postgres.sh
      runas: ubuntu
  AfterInstall:
    - location: scripts/install_rails.sh
      runas: ubuntu
  ApplicationStart:
    - location: scripts/start_docker_compose.sh
    - location: scripts/bootstrap.sh
    - location: scripts/start_rails.sh
    - locattion: scripts/start_karafka.sh    
      runas: root

