version: 0.0
os: linux
files:
  - source: /application
    destination: /home/ubuntu
permissions:
  - object: /home/ubuntu
    pattern: “**”
    owner: ubuntu
    group: ubuntu
    mode: 775
hooks:
  BeforeInstall:
    - location: scripts/install_docker.sh
      runas: ubuntu
    - location: scripts/install_postgres.sh
      runas: ubuntu
  AfterInstall:
    - location: scripts/install_rails.sh
      runas: ubuntu
  ValidateService:
    - location: application/bin/bootstrap
      runas: ubuntu
    - location: application/docker_compose.sh
      runas: ubuntu