version: 0.1

phases:
  install:
    commands:
      - apt-get update -y
      - apt-get install software-properties-common -y
      - sudo apt-get -y install libpq-dev
      - sudo apt-get update
      - sudo gem install bundler
      - sudo bundle install
    commands:
      - echo Running rspec tests...
      - bundle exec rspec spec/