version: 0.2
phases:
  install:
    runtime-versions:
        ruby: 3.2
    commands:
      - echo Installing Bundler...
      - gem update --system
      - apt install ruby-dev
      - gem install bundler
      - bundle install
  pre_build:
    commands:
      - echo Preparing database to run tests...
      - RAILS_ENV=test rails db:setup
      - RAILS_ENV=test rails db:migrate
  build:
    commands:
      - echo Running tests...
      - rails test