version: 0.1

phases:
  install:
    commands:
      - echo Starting postgresql...
      - echo Installing Bundler...
      - gem install bundler
      - bundle install --with test
  build:
    commands:
      - echo Running rspec tests...
      - bundle exec rspec spec/