version: 0.2

phases:
  install:
    runtime-versions:
      ruby: 3.2
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - gem install bundler
      - echo Running rspec tests...
      - bundle exec rspec spec/